# Pytorch基础操作

## 1. 基础语法

In [1]:
import torch

In [5]:
torch.__version__

'2.3.0+cu118'

In [6]:
x = torch.rand(5, 3)
x

tensor([[0.5050, 0.7070, 0.9993],
        [0.5795, 0.0153, 0.7702],
        [0.1581, 0.5423, 0.8336],
        [0.5369, 0.9946, 0.5457],
        [0.2589, 0.7079, 0.9123]])

Pytorch的基本数据单元是tensor

In [7]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [9]:
x.size()

torch.Size([2])

In [10]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## 2. Tensor

### 2.1 初始化Tensor

**1. 直接从原生数据创建**

In [18]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**2. 从NumPy数组创建**

In [21]:
import numpy as np
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [22]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**3. 从tensor变量创建**

In [23]:
x_ones = torch.ones_like(x_data) # ones_like创建继承x_data属性的新张量，且所有元素为1
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # 创建一个新的张量，其形状与x_data相同，但是填充了随机数
print(f"Random Tensor:\n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.9335, 0.3193],
        [0.8964, 0.8951]])



**4. 从随机数据或常量创建**

In [24]:
# shape 是 tensor 维数的元组。在下面的实例中，它决定了输出 tensor 的维数。

In [25]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.2172, 0.6897, 0.4017],
        [0.3227, 0.9929, 0.4083]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



### 2.2 Tensor的属性

In [26]:
# Tensor 属性描述了它们的形状、数据类型和存储它们的设备。

In [27]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 2.3 Tensor的操作

**1. 索引和分片的标准操作**

In [29]:
tensor = torch.rand(4,4)
print(tensor[:,:])
# 第一行
first_row = tensor[0]
# 第一列
first_column = tensor[ : ,0]
# 最后一列
last_column = tensor[ : ,-1]
print(f"First row:\n{first_row}\n")
print(f"First column:\n{first_column}\n")
print(f"Last column:\n{last_column}\n")

tensor([[0.9693, 0.5596, 0.2732, 0.0790],
        [0.4292, 0.0833, 0.0558, 0.8595],
        [0.6236, 0.8381, 0.6848, 0.2082],
        [0.8773, 0.3311, 0.0300, 0.7743]])
First row:
tensor([0.9693, 0.5596, 0.2732, 0.0790])

First column:
tensor([0.9693, 0.4292, 0.6236, 0.8773])

Last column:
tensor([0.0790, 0.8595, 0.2082, 0.7743])



**2. 连接 tensors**

In [30]:
#torch.cat 将一系列tensor沿着给定的维数连接起来。

In [34]:
tensor1 = torch.ones(4,4)
tensor2 = torch.zeros(4,4)
print(tensor1[:,:])
print(tensor2[:,:])
# 张量按照行并排起来
t1 = torch.cat([tensor1, tensor2],dim=1)
print(t1)
# 张量按照列并排起来
t2 = torch.cat([tensor1, tensor2],dim=0)
print(t2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


**3. 算术运算**

In [35]:
tensor = torch.ones(2,2)
print(tensor)
# tensor.T returns the transpose of a tensor
# @可以用于矩阵相乘，matmul()当两个tensor都为n>=2的矩阵时，表示矩阵相乘
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(f"Y1={y1}\n")
print(f"Y2={y2}\n")

tensor([[1., 1.],
        [1., 1.]])
Y1=tensor([[2., 2.],
        [2., 2.]])

Y2=tensor([[2., 2.],
        [2., 2.]])



In [37]:
data1 = [[1,2]]
data2 = [[5,6,7],[8,9,10]]
tensor1 = torch.tensor(data1)
tensor2 = torch.tensor(data2)
tensor3 = tensor1.matmul(tensor2)
print(f"Tensor3={tensor3}\n")

Tensor3=tensor([[21, 24, 27]])



In [39]:
y3 = torch.rand_like(y1)
print(f"Y3={y3}\n")
torch.matmul(tensor, tensor.T, out=y3) # torch.matmul(input, other, *, out=None) → Tensor
# input和other是要进行乘法运算的两个张量，out是可选参数，用于指定输出张量。这里就将运算结果输出到y3
print(f"Y3'={y3}\n")

Y3=tensor([[0.3574, 0.8434],
        [0.3876, 0.5467]])

Y3'=tensor([[2., 2.],
        [2., 2.]])



In [44]:
# * 可以用来表示矩阵对应位置元素相乘；mul()函数也可以这样用
data_z = [[1,2,3],[4,5,6]]
tensor_z = torch.tensor(data_z)
z1 = tensor_z * tensor_z
z2 = tensor_z.mul(tensor_z)
print(f"Z1={z1}\n")
print(f"Z2={z2}\n")

Z1=tensor([[ 1,  4,  9],
        [16, 25, 36]])

Z2=tensor([[ 1,  4,  9],
        [16, 25, 36]])



In [48]:
tensor_z = tensor_z.float()  # 确保 tensor_z 是浮点数
z3 = torch.rand_like(tensor_z)
print(f"Z3={z3}\n")
torch.mul(tensor_z, tensor_z, out=z3) # 将点乘的结果输出到z3
print(f"Z3'={z3}\n")

Z3=tensor([[0.7304, 0.4182, 0.9047],
        [0.1997, 0.9050, 0.1450]])

Z3'=tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])



**4. 单个元素的tensor**

通过将 tensors 的所有值聚合成一个值，就可以使用 item() 将它转换成 Python 数值:

In [50]:
print(tensor)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[1., 1.],
        [1., 1.]])
4.0 <class 'float'>


### 2.4 Tensor与Numpy的转换

**1. Tensor转换为Numpy数组**

In [51]:
# .numpy()
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


**2. Numpy数组转换为Tensor**

In [52]:
# .from_numpy()
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


## 3. 自动求导机制Autograd

In [11]:
x = torch.randn(3,4,requires_grad=True)
x

tensor([[-1.2443,  1.2509,  0.1761,  2.3178],
        [-1.3872, -1.8785,  0.0048,  0.4109],
        [ 1.6161,  2.4497,  0.9768, -0.3773]], requires_grad=True)

requires_grad 表达的含义是，这一参数是否保留（或者说持有，即在前向传播完成后，是否在显存中记录这一参数的梯度，而非立即释放）梯度，等待优化器执行optim.step()更新参数。

当requires_grad = False，则不保留梯度，因此即便在optimizer中注册了参数，也没有梯度可以用来更新参数，因此参数不变。不过不影响梯度继续反向传播，即假设某一层（例如第三层）参数的requires_grad为False或True，前面层（第1或2层）参数的梯度都不变。

当requires_grad = True，则在前向计算后保留梯度，用于optimizer更新参数。但如果没有在optimizer中注册参数，那么即便保存了梯度,也无法更新参数。

In [12]:
b = torch.randn(3,4,requires_grad=True)
b

tensor([[-0.9841, -0.3123, -1.2117, -0.9480],
        [ 0.2664,  0.1468, -1.0574,  0.3353],
        [-0.0445, -1.2126,  0.1410,  1.8781]], requires_grad=True)

In [13]:
t = b + x

In [14]:
y = t.sum()
y

tensor(1.3127, grad_fn=<SumBackward0>)

In [15]:
# 标量对向量求导，直接调用backward（）函数，进行反向传播
y.backward()

In [17]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])